### ISSUE TITLE
Centering not picked up

### ISSUE THREAD

**Issue by tliebig** [louisremi/jquery.backgroundSize.js#5]
Hey Louis,

great to see someone taking care of IEs lacking support for some of CSS' more helpful options. I'm employing the script here:

http://beta.insachenkunst.de/kuenstler/tom-schulhauser/

and although it resizes the image fine, it fails to correctly center the image. Any idea as to why that might happen?

**Comment by louisremi** [comment]
Hi,
for some reason my script throws an error in IE on page load.
Could you try loading the development version of the script instead of the minified one to help me investigate?
Thanks.

**Comment by tliebig** [comment]
Sure. I have updated the page to load the development version. The error occurs on line 308, at $(window).on as far as I can see.

**Comment by louisremi** [comment]
This error is due to the fact that you're using an old version of jQuery.
The "on" method has been introduced in jQuery 1.7

That doesn't explain why your images aren't centered. I'm still  
investigating.

**Comment by louisremi** [comment]
Are you initializing your element with a background size?
`$(elem).css( "background-size", "cover" );`

**Comment by tliebig** [comment]
I believe I am. There's both javascript code that adds the css directly to the element as well as a rule for the class that contains "background-size: cover":

from http://beta.insachenkunst.de/wordpress/wp-content/themes/insachenkunst/js/artist-gallery.js line 10:

``` css
element.style {
    background-image: url("http://beta.insachenkunst.de/wordpress/wp-content/uploads/Schulhauser-4-Postpanoptisches-Lächeln-4-mittel.jpg");
    background-position: center center;
    background-repeat: no-repeat;
    background-size: contain;
}
```

and http://beta.insachenkunst.de/wordpress/wp-content/themes/insachenkunst/page-kuenstler-einzelansicht.css line 19

``` css
.gallery .gallery-large-thumb {
    background-position: center center;
    background-size: contain;
    border: medium none;
    display: block;
    height: 339px;
    margin-bottom: 13px;
    width: 552px;
}
```
